%YAML 1.2
---

# operator templates
####################

# izhikevich operator with biophysiologically relevant parameters
ik_op:
  base: OperatorTemplate
  equations:
    - "r' = (Delta*k^2*(v-v_r)/(pi*C) + r*(k*(2.0*v-v_r-v_t) - q - g*s)) / C"
    - "v' = (k*v*(v-v_r-v_t) - C*pi*r*(Delta+pi*C*r/k) + k*v_r*v_t + g*s*(E_r-v) + q*C*log(v_p/v_z)*r/k + I_ext - u) / C"
    - "u' = a*(b*(v-v_r) - u) + d*r"
    - "s' = -s/tau_s + r_in"
  variables:
    r: output(0.0)
    v: variable(-60.0)
    u: variable(0.0)
    s: variable(0.0)
    Delta: 0.1
    C: 100.0
    k: 0.7
    v_r: -60.0
    v_t: -40.0
    v_p: 400.0
    v_z: 600.0
    q: 0.0
    g: 20.0
    E_r: 0.0
    b: -2.0
    a: 0.03
    d: 100.0
    tau_s: 6.0
    I_ext: input(0.0)
    r_in: input(0.0)

# izhikevich operator with less relevant parameters
ik_ei_op:
  base: OperatorTemplate
  equations:
    - "r' = (Delta*k^2*(v-v_r)/(pi*C) + r*(k*(2.0*v-v_r-v_t) - q - g_ampa*s_ampa - g_gabaa*s_gabaa)) / C"
    - "v' = (k*v*(v-v_r-v_t) - C*pi*r*(pi*C*r/k) + k*v_r*v_t + g_ampa*s_ampa*(E_ampa-v) + g_gabaa*s_gabaa*(E_gabaa-v) + q*C*log(v_p/v_z)*r/k + I_ext - u) / C"
    - "u' = a*(b*(v-v_r) - u) + d*r"
    - "s_ampa' = -s_ampa/tau_ampa + r_e"
    - "s_gabaa' = -s_gabaa/tau_gabaa + r_i"
  variables:
    r: output(0.0)
    v: variable(-60.0)
    u: variable(0.0)
    s_ampa: variable(0.0)
    s_gabaa: variable(0.0)
    Delta: 0.1
    C: 100.0
    k: 0.7
    v_r: -60.0
    v_t: -40.0
    v_p: 400.0
    v_z: 600.0
    q: 0.0
    g_ampa: 10.0
    g_gabaa: 10.0
    E_ampa: 0.0
    E_gabaa: -60.0
    b: -2.0
    a: 0.03
    d: 100.0
    tau_ampa: 6.0
    tau_gabaa: 8.0
    I_ext: input(0.0)
    r_e: input(0.0)
    r_i: input(0.0)

# stn-specific parameters
stn_op:
  base: ik_op
  variables:
    Delta: 0.1
    C: 25.0
    k: 0.45
    v_r: -55.0
    v_t: -40.0
    v_p: 15.0
    v_z: 50.0
    q: 0.0
    g: 0.5
    E_r: -65.0
    b: 4.0
    a: 0.02
    d: 15.0
    tau_s: 8.0

# gpe-specific parameters
gpe_op:
  base: ik_ei_op
  variables:
    Delta: 0.1
    C: 70.0
    k: 0.95
    v_r: -55.0
    v_t: -45.0
    v_p: 25.0
    v_z: 60.0
    q: 0.0
    g_ampa: 1.5
    g_gabaa: 0.8
    E_ampa: 0.0
    E_gabaa: -65.0
    b: 4.0
    a: 0.005
    d: 0.4
    tau_ampa: 2.0
    tau_gabaa: 5.0

rs_op:
  base: ik_ei_op
  variables:
    Delta: 1.0
    C: 100.0
    k: 0.7
    v_r: -60.0
    v_t: -40.0
    v_p: 60.0
    v_z: 60.0
    q: 0.0
    g_ampa: 1.0
    g_gabaa: 1.0
    E_ampa: 0.0
    E_gabaa: -65.0
    b: -2.0
    a: 0.03
    d: 20.0
    tau_ampa: 6.0
    tau_gabaa: 8.0

ib_op:
  base: ik_ei_op
  variables:
    Delta: 1.0
    C: 150.0
    k: 1.2
    v_r: -75.0
    v_t: -45.0
    v_p: 56.0
    v_z: 56.0
    q: 0.0
    g_ampa: 1.5
    g_gabaa: 0.8
    E_ampa: 0.0
    E_gabaa: -65.0
    b: 5.0
    a: 0.01
    d: 30.0
    tau_ampa: 6.0
    tau_gabaa: 8.0

fs_op:
  base: ik_ei_op
  variables:
    Delta: 1.0
    C: 20.0
    k: 1.0
    v_r: -55.0
    v_t: -40.0
    v_p: 25.0
    v_z: 45.0
    q: 0.0
    g_ampa: 1.0
    g_gabaa: 1.0
    E_ampa: 0.0
    E_gabaa: -65.0
    b: 0.025
    a: 0.2
    d: 0.0
    tau_ampa: 6.0
    tau_gabaa: 8.0

lts_op:
  base: ik_ei_op
  variables:
    Delta: 1.0
    C: 100.0
    k: 1.0
    v_r: -56.0
    v_t: -42.0
    v_p: 40.0
    v_z: 53.0
    q: 0.0
    g_ampa: 1.0
    g_gabaa: 1.0
    E_ampa: 0.0
    E_gabaa: -65.0
    b: 8.0
    a: 0.03
    d: 20.0
    tau_ampa: 6.0
    tau_gabaa: 8.0

# node templates
################

# population of biophysiologically informed izhikevich neurons with mono-exponential synapses
ik_pop:
  base: NodeTemplate
  operators:
    - ik_op

# stn population
stn:
  base: NodeTemplate
  operators:
    - stn_op

# gpe population
gpe:
  base: NodeTemplate
  operators:
    - gpe_op

# regular spiking neuron population
rs:
  base: NodeTemplate
  operators:
    - rs_op

# intrinsically bursting neuron population
ib:
  base: NodeTemplate
  operators:
    - ib_op

# fast-spiking neuron population
fs:
  base: NodeTemplate
  operators:
    - fs_op

# low-threshold-spiking neuron population
lts:
  base: NodeTemplate
  operators:
    - lts_op

# circuit templates
###################

# biophysiologically informed izhikevich population with mono-exponential synapses
ik:
  base: CircuitTemplate
  nodes:
    p: ik_pop
  edges:
    - [p/ik_op/r, p/ik_op/r_in, null, {weight: 1.0}]

# stn-gpe circuit
stn_gpe:
  base: CircuitTemplate
  nodes:
    stn: stn
    gpe: gpe
  edges:
    - [stn/stn_op/r, gpe/gpe_op/r_e, null, {weight: 15.0}]
    - [gpe/gpe_op/r, stn/stn_op/r_in, null, {weight: 15.0}]
    - [gpe/gpe_op/r, gpe/gpe_op/r_i, null, {weight: 15.0}]

# rs-fs circuit
eic:
  base: CircuitTemplate
  nodes:
    rs: rs
    fs: fs
  edges:
    - [rs/rs_op/r, rs/rs_op/r_e, null, {weight: 18.0}]
    - [rs/rs_op/r, fs/fs_op/r_e, null, {weight: 10.0}]
    - [fs/fs_op/r, rs/rs_op/r_i, null, {weight: 18.0}]
    - [fs/fs_op/r, fs/fs_op/r_i, null, {weight: 10.0}]

# rs-fs circuit
eiic:
  base: CircuitTemplate
  nodes:
    rs: rs
    fs: fs
    lts: lts
  edges:
    - [rs/rs_op/r, rs/rs_op/r_e, null, {weight: 10.0}]
    - [rs/rs_op/r, fs/fs_op/r_e, null, {weight: 8.0}]
    - [rs/rs_op/r, lts/lts_op/r_e, null, {weight: 4.0}]
    - [fs/fs_op/r, rs/rs_op/r_i, null, {weight: 8.0}]
    - [fs/fs_op/r, fs/fs_op/r_i, null, {weight: 4.0}]
    - [fs/fs_op/r, lts/lts_op/r_i, null, {weight: 4.0}]
    - [lts/lts_op/r, rs/rs_op/r_i, null, {weight: 8.0}]
    - [lts/lts_op/r, fs/fs_op/r_i, null, {weight: 4.0}]
