%YAML 1.2
---


# izhikevich operator with biophysiologically relevant parameters
ik_op:
  base: OperatorTemplate
  equations:
    - "r' = (Delta*k^2*(v-v_r)/(pi*C) + r*(k*(2.0*v-v_r-v_t) - q - g*s)) / C"
    - "v' = (k*v*(v-v_r-v_t) - C*pi*r*(Delta+pi*C*r/k) + k*v_r*v_t + g*s*(E_r-v) + q*C*log(v_p/v_z)*r/k + I_ext - u) / C"
    - "u' = a*(b*(v-v_r) - u) + d*r"
    - "s' = -s/tau_s + r_in"
  variables:
    r: output(0.0)
    v: variable(-60.0)
    u: variable(0.0)
    s: variable(0.0)
    Delta: 0.1
    C: 100.0
    k: 0.7
    v_r: -60.0
    v_t: -40.0
    v_p: 400.0
    v_z: 600.0
    q: 0.0
    g: 20.0
    E_r: 0.0
    b: -2.0
    a: 0.03
    d: 100.0
    tau_s: 6.0
    I_ext: input(0.0)
    r_in: input(0.0)


# population of biophysiologically informed izhikevich neurons with mono-exponential synapses
ik_pop:
  base: NodeTemplate
  operators:
    - ik_op


# biophysiologically informed izhikevich population with mono-exponential synapses
ik:
  base: CircuitTemplate
  nodes:
    p: ik_pop
  edges:
    - [p/ik_op/r, p/ik_op/r_in, null, {weight: 1.0}]
