%YAML 1.2
---

# operator templates
####################

# operator for regular-spiking IK neurons
rs_op:
  base: OperatorTemplate
  equations:
    - "v' = (k*(v-v_r)*(v-v_theta) - u + I_ext + eta + g_e*s_e*(E_e - v) + g_i*s_i*(E_i - v)) / C"
    - "u' = (b*(v-v_r) - u) / tau_u + kappa*spike"
    - "s' = -s/tau_s + spike"
  variables:
    s: output(0.0)
    v: variable(-60.0)
    u: variable(0.0)
    C: 100.0
    k: 0.7
    v_r: -60.0
    v_theta: -40.0
    eta: 0.0
    g_e: 1.0
    E_e: 0.0
    g_i: 1.0
    E_i: -65.0
    b: -2.0
    tau_u: 33.33
    kappa: 10.0
    tau_s: 6.0
    I_ext: input(0.0)
    spike: input(0.0)
    s_in: input(0.0)

# parameters for fast-spiking neurons
fs_op:
  base: rs_op
  variables:
    Delta: 1.0
    C: 20.0
    k: 1.0
    v_r: -55.0
    v_t: -40.0
    b: 0.025
    a: 0.2
    d: 0.0
    tau_s: 8.0

# node templates
################

# regular-spiking neuron population
rs:
  base: NodeTemplate
  operators:
    - rs_op

# fast-spiking neuron population
fs:
  base: NodeTemplate
  operators:
    - fs_op
