%YAML 1.2
---

# operator templates
####################

# izhikevich operator with biophysiologically relevant parameters
ik_op:
  base: OperatorTemplate
  equations:
    - "r' = (Delta*k^2*absv(v-v_r)/(pi*C) + r*(k*(2.0*v-v_r-v_t) - s_e - s_i)) / C"
    - "v' = (k*v*(v-v_r-v_t) - C*pi*r*(Delta*sign(v-v_r)+pi*C*r/k) + k*v_r*v_t + s_e*(E_e-v) + s_i*(E_i-v) + eta + I_ext - u) / C"
    - "u' = a*(b*(v-v_r) - u) + d*r"
    - "s' = -s/tau_s + r"
  variables:
    r: output(0.0)
    v: variable(-60.0)
    u: variable(0.0)
    s: variable(0.0)
    Delta: 0.1
    C: 100.0
    k: 0.7
    v_r: -60.0
    v_t: -40.0
    E_e: 0.0
    E_i: -65.0
    b: -2.0
    a: 0.03
    d: 100.0
    tau_s: 6.0
    eta: 0.0
    I_ext: input(0.0)
    s_e: input(0.0)
    s_i: input(0.0)

# node templates
################

# population of biophysiologically informed izhikevich neurons
ik:
  base: NodeTemplate
  operators:
    - ik_op
