%YAML 1.2
---

# general operator for IK neurons
ik_op:
  base: OperatorTemplate
  equations:
    - "v' = (k*(v-v_r)*(v-v_t) - u + eta + I_ext + s_e*(E_e - v) + s_i*(E_i - v)) / C"
    - "u' = a*(b*(v-v_r) - u) + d*spike"
    - "s' = -s/tau_s + spike"
  variables:
    s: output(0.0)
    v: variable(-60.0)
    u: variable(0.0)
    C: 100.0
    k: 0.7
    v_r: -60.0
    v_t: -40.0
    eta: 0.0
    E_e: 0.0
    E_i: -65.0
    b: -2.0
    a: 0.03
    d: 10.0
    tau_s: 6.0
    spike: input(0.0)
    s_e: input(0.0)
    s_i: input(0.0)
    I_ext: input(0.0)

# population of generalized Izhikevich neurons
ik:
  base: NodeTemplate
  operators:
    - ik_op
