%YAML 1.2
---

# operator for regular-spiking IK neurons
ik_op:
  base: OperatorTemplate
  equations:
    - "v' = (k*(v-v_r)*(v-v_theta) - u + eta + I_ext + g_e*s_e*(E_e - v) + g_i*mean(s_i)*(E_i - v)) / C"
    - "u' = (b*(mean(v)-v_r) - u) / tau_u + kappa*mean(spike)"
    - "s' = -s/tau_s + spike + s_ext"
  variables:
    s: output(0.0)
    v: variable(-60.0)
    u: variable(0.0)
    C: 100.0
    k: 0.7
    v_r: -60.0
    v_theta: -40.0
    eta: 0.0
    g_e: 1.0
    E_e: 0.0
    g_i: 1.0
    E_i: -60.0
    b: -2.0
    tau_u: 33.33
    kappa: 10.0
    tau_s: 6.0
    spike: input(0.0)
    s_e: input(0.0)
    s_i: input(0.0)
    I_ext: input(0.0)
    s_ext: input(0.0)

# operator for IK neurons with microglia modulation
mg_op:
  base: OperatorTemplate
  equations:
    - "v' = (k*(v-v_r)*(v-v_t) - u + I_ext + g_e*s_e*(1-sigmoid(x))*(E_e-v) + g_i*mean(s_i)*(E_i-v)) / C"
    - "u' = (b*(mean(v)-v_r) - u) / tau_u + kappa*mean(spike)"
    - "s' = -s/tau_s + spike + s_ext"
    - "x' = x2 - x/tau_d"
    - "x2' = alpha*s_e*(1-sigmoid(x)) - x2/tau_r"
  variables:
    s: output(0.0)
    v: variable(-60.0)
    u: variable(0.0)
    x: variable(0.0)
    x2: variable(0.0)
    C: 100.0
    k: 0.7
    v_r: -60.0
    v_t: -40.0
    g_e: 1.0
    E_e: 0.0
    g_i: 1.0
    E_i: -60.0
    b: -2.0
    tau_u: 33.33
    kappa: 10.0
    alpha: 0.0
    tau_s: 6.0
    tau_r: 50.0
    tau_d: 500.0
    spike: input(0.0)
    s_e: input(0.0)
    s_i: input(0.0)
    I_ext: input(0.0)
    s_ext: input(0.0)

# population of generalized Izhikevich neurons
ik:
  base: NodeTemplate
  operators:
    - ik_op

# population of Izhikevich neurons with microglia neuromodulation
mg:
  base: NodeTemplate
  operators:
    - mg_op

