%YAML 1.2
---

# adIK neurons with neuron-specific recovery variable
adik_op2:
  base: OperatorTemplate
  equations:
    - "inp = -u + eta + I_ext + g*mean(s)*(E_r - v)"
    - "v' = (k*(v-v_r)*(v-v_theta) + inp) / C"
    - "u' = (b*(v-v_r) - u + kappa*inp) / tau_u"
    - "x' = (spike-x)/tau_x"
    - "s' = -s/tau_s + spike"
  variables:
    s: output(0.0)
    v: variable(-60.0)
    u: variable(0.0)
    x: variable(0.0)
    inp: variable(0.0)
    C: 100.0
    k: 0.7
    v_r: -60.0
    v_theta: -40.0
    eta: 0.0
    g: 1.0
    E_r: 0.0
    b: -2.0
    tau_u: 33.33
    kappa: 10.0
    tau_x: 300.0
    tau_s: 6.0
    spike: input(0.0)
    s_in: input(0.0)
    I_ext: input(0.0)

# adIK neurons with neuron-specific recovery variable
adik_op_mu:
  base: OperatorTemplate
  equations:
    - "v' = (k*(v-v_r)*(v-v_theta) - u + eta + I_ext + g*mean(s)*(E_r - v)) / C"
    - "u' = (b*(v-v_r+mu) - u) / tau_u + kappa*mean(x)"
    - "x' = (spike-x)/tau_x"
    - "s' = -s/tau_s + spike"
  variables:
    s: output(0.0)
    v: variable(-60.0)
    u: variable(0.0)
    x: variable(0.0)
    C: 100.0
    k: 0.7
    v_r: -60.0
    v_theta: -40.0
    eta: 0.0
    mu: 0.0
    g: 1.0
    E_r: 0.0
    b: -2.0
    tau_u: 33.33
    kappa: 10.0
    tau_x: 300.0
    tau_s: 6.0
    spike: input(0.0)
    s_in: input(0.0)
    I_ext: input(0.0)

# adIK neurons with global recovery variable
adik_op_global:
  base: OperatorTemplate
  equations:
    - "v' = (k*(v-v_r)*(v-v_theta) - u + eta + I_ext + g*mean(s)*(E_r - v)) / C"
    - "u' = (b*(mean(v)-v_r) - u) / tau_u + kappa*mean(x)"
    - "x' = (spike-x)/tau_x"
    - "s' = -s/tau_s + spike"
  variables:
    s: output(0.0)
    v: variable(-60.0)
    u: variable(0.0)
    x: variable(0.0)
    C: 100.0
    k: 0.7
    v_r: -60.0
    v_theta: -40.0
    eta: 0.0
    g: 1.0
    E_r: 0.0
    b: -2.0
    tau_u: 33.33
    kappa: 10.0
    tau_x: 300.0
    tau_s: 6.0
    spike: input(0.0)
    s_in: input(0.0)
    I_ext: input(0.0)

# adIK neurons with neuron-specific recovery variable
adik_op:
  base: OperatorTemplate
  equations:
    - "v' = (k*(v-v_r)*(v-v_theta) - u + eta + I_ext + g*mean(s)*(E_r - v)) / C"
    - "u' = (b*(v-v_r) - u) / tau_u + kappa*x"
    - "x' = (spike-x)/tau_x"
    - "s' = -s/tau_s + spike"
  variables:
    s: output(0.0)
    v: variable(-60.0)
    u: variable(0.0)
    x: variable(0.0)
    C: 100.0
    k: 0.7
    v_r: -60.0
    v_theta: -40.0
    eta: 0.0
    g: 1.0
    E_r: 0.0
    b: -2.0
    tau_u: 33.33
    kappa: 10.0
    tau_x: 300.0
    tau_s: 6.0
    spike: input(0.0)
    s_in: input(0.0)
    I_ext: input(0.0)

# population of adIK neurons with global recovery variable
adik_global:
  base: NodeTemplate
  operators:
    - adik_op_global

# population of adIK neurons with global spike frequency adaptation variable
adik_mu:
  base: NodeTemplate
  operators:
    - adik_op_mu

# population of adIK neurons with neuron-specific recovery variable
adik:
  base: NodeTemplate
  operators:
    - adik_op

# population of adIK neurons with neuron-specific recovery variable
adik2:
  base: NodeTemplate
  operators:
    - adik_op2
