%YAML 1.2
---

# operator for regular-spiking IK neurons
rs_op:
  base: OperatorTemplate
  equations:
    - "v' = (k*(v-v_r)*(v-v_theta) - u + eta + I_ext + g*(s_in + s_ext)*(E_r - v)) / C"
    - "u' = (b*(mean(v)-v_r) - u) / tau_u + kappa*mean(spike)"
    - "s' = -s/tau_s + spike"
  variables:
    s: output(0.0)
    v: variable(-60.0)
    u: variable(0.0)
    C: 100.0
    k: 0.7
    v_r: -60.0
    v_theta: -40.0
    eta: 0.0
    g: 15.0
    E_r: 0.0
    b: -2.0
    tau_u: 33.33
    kappa: 100.0
    tau_s: 6.0
    spike: input(0.0)
    s_in: input(0.0)
    I_ext: input(0.0)
    s_ext: input(0.0)

# operator for regular-spiking IK neurons
ik_op:
  base: rs_op
  equations:
    - "v' = (k*(v-v_r)*(v-v_theta) - u + eta + I_ext + g_e*s_e*(E_e - v) + g_i*s_i*(E_i - v)) / C"
    - "u' = (b*(mean(v)-v_r) - u) / tau_u + kappa*mean(spike)"
    - "s' = -s/tau_s + spike + s_ext"
  variables:
    s: output(0.0)
    v: variable(-60.0)
    u: variable(0.0)
    C: 100.0
    k: 0.7
    v_r: -60.0
    v_theta: -40.0
    eta: 0.0
    g_e: 1.0
    E_e: 0.0
    g_i: 1.0
    E_i: -60.0
    b: -2.0
    tau_u: 33.33
    kappa: 10.0
    tau_s: 6.0
    spike: input(0.0)
    s_e: input(0.0)
    s_i: input(0.0)
    I_ext: input(0.0)
    s_ext: input(0.0)

# population of regular-spiking neurons
rs:
  base: NodeTemplate
  operators:
    - rs_op

# population of generalized Izhikevich neurons
ik:
  base: NodeTemplate
  operators:
    - ik_op
